### ISSUE TITLE
Can't test dyn_multi or other mappings - need to move some code from dispel4py_autoscaling repo

### ISSUE THREAD

**Issue by gskorokhod** [gskorokhod/dispel4py#1]
# Description

Cannot run mapping, crashes with the following message

```
(d4p-py310) mayday@localhost:~/Coding/Projects/dispel4py/repos/dispel4py>  dispel4py dyn_multi dispel4py.examples.graph_testing.pipeline_test -i 10 -n 6
Processing 10 iterations.
RUN ARGS: 
Namespace(target='dyn_multi', module='dispel4py.examples.graph_testing.pipeline_test', attr=None, file=None, data=None, iter=10, provenance=None)
==========
Traceback (most recent call last):
  File "/home/mayday/Applications/anaconda3/envs/d4p-py310/bin/dispel4py", line 33, in <module>
    sys.exit(load_entry_point('dispel4py==1.3.0', 'console_scripts', 'dispel4py')())
  File "/home/mayday/Applications/anaconda3/envs/d4p-py310/lib/python3.10/site-packages/dispel4py-1.3.0-py3.10.egg/dispel4py/new/processor.py", line 928, in main
    process = getattr(import_module(target), "process")
  File "/home/mayday/Applications/anaconda3/envs/d4p-py310/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/mayday/Applications/anaconda3/envs/d4p-py310/lib/python3.10/site-packages/dispel4py-1.3.0-py3.10.egg/dispel4py/new/new_dynamic.py", line 26, in <module>
    from dispel4py.new.logger import logger, print_stack_trace
ModuleNotFoundError: No module named 'dispel4py.new.logger'
```

See: #2 

# TODO

- [x] Move the relevant `logger` class from dispel4py_autoscaling and try again?

**Comment by gskorokhod** [comment]
Moved logger file to dispel4py/new, now everything works fine
