### ISSUE TITLE
dyn_auto_redis mapping not working

### ISSUE THREAD

**Issue by gskorokhod** [gskorokhod/dispel4py#5]
```
(d4p-py310) mayday@8afbe9b7:~/Coding/Projects/dispel4py/repos/dispel4py> dispel4py dyn_auto_redis dispel4py.examples.graph_testing.pipeline_tes -i 10 -n 6 -thr 200
Failed to load graph from "dispel4py.examples.graph_testing.pipeline_tes":
No module "dispel4py.examples.graph_testing.pipeline_tes"
Error loading graph from file:
Traceback (most recent call last):
  File "/home/mayday/Applications/anaconda3/envs/d4p-py310/lib/python3.10/site-packages/dispel4py-1.3.0-py3.10.egg/dispel4py/utils.py", line 84, in load_graph
    return loadGraphFromFile(module_name, graph_source, attr)
  File "/home/mayday/Applications/anaconda3/envs/d4p-py310/lib/python3.10/site-packages/dispel4py-1.3.0-py3.10.egg/dispel4py/utils.py", line 49, in loadGraphFromFile
    module = util.module_from_spec(spec)
  File "<frozen importlib._bootstrap>", line 568, in module_from_spec
AttributeError: 'NoneType' object has no attribute 'loader'

(d4p-py310) mayday@8afbe9b7:~/Coding/Projects/dispel4py/repos/dispel4py> dispel4py dyn_auto_redis dispel4py.examples.graph_testing.pipeline_tes -i 10 -n 6 -thr 200
Failed to load graph from "dispel4py.examples.graph_testing.pipeline_tes":
No module "dispel4py.examples.graph_testing.pipeline_tes"
Error loading graph from file:
Traceback (most recent call last):
  File "/home/mayday/Applications/anaconda3/envs/d4p-py310/lib/python3.10/site-packages/dispel4py-1.3.0-py3.10.egg/dispel4py/utils.py", line 84, in load_graph
    return loadGraphFromFile(module_name, graph_source, attr)
  File "/home/mayday/Applications/anaconda3/envs/d4p-py310/lib/python3.10/site-packages/dispel4py-1.3.0-py3.10.egg/dispel4py/utils.py", line 49, in loadGraphFromFile
    module = util.module_from_spec(spec)
  File "<frozen importlib._bootstrap>", line 568, in module_from_spec
AttributeError: 'NoneType' object has no attribute 'loader'
```

**Comment by gskorokhod** [comment]
I've located the issue to this function:
```
def loadGraphFromFile(module_name, path, attr=None):
    if sys.version_info > (3, 0):
        from importlib import util

        print(f'Importing {module_name} from "{path}...')
        spec = util.spec_from_file_location(module_name, path)
        print(spec)

        module = util.module_from_spec(spec)
        sys.modules[spec.name] = module
        spec.loader.exec_module(module)
    else:
        module = load_source(module_name, path)

    attr = findWorkflowGraph(module, attr)
    return attr
```

When I print the path, it gives a file inside dispel4py/examples/graph_testing
However, you can't import it with importlib for some reason - seems to be related to #6 (files in examples not being importable), but I can't figure out why this happens..
